apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-abnf" (include "mrr-chart.fullname" .) }}
  labels:
    {{- include "mrr-chart-abnf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "mrr-chart-abnf.selectorLabels" . | nindent 4 }}
