---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mrr-chart.fullname" . }}
  labels:
    {{- include "mrr-chart.labels" . | nindent 4 }}
data:
  application.properties: |
    logging.level.org.iala_aism = {{ .Values.mrr.loggingLevel }}

    server.port={{ .Values.mrr.serverPort }}

    spring.neo4j.uri=bolt://{{ .Release.Name }}:7687
    spring.neo4j.authentication.username=neo4j
    spring.neo4j.authentication.password={{ .Values.neo4jStandalone.neo4j.password }}

    management.server.port={{ .Values.mrr.managementPort }}
    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true

    spring.security.oauth2.resourceserver.jwt.issuer-uri={{ .Values.mrr.oauth2Server }}
