apiVersion: v2
name: mrr-chart
description: A Helm chart for the Maritime Resource Registry

type: application

version: 0.1.1

appVersion: "0.0.1"

dependencies:
  - name: neo4j-standalone
    alias: neo4jStandalone
    version: 4.4.10
    repository: https://neo4j.github.io/helm-charts/
  - name: redis
    version: 17.1.4
    repository: https://charts.bitnami.com/bitnami
